= Description of usage in Jenkins
Jon Brohauge <jnz@topdanmark.dk>
v1.0, 2019-08-27
:imagesdir: ../images

Prior to Jenkins 1.625.3 there is no support of the https://plugins.jenkins.io/dependency-track[OWASP Dependency-Track] Jenkins Plugin.
To be able to still utilize the power of Dependency-Track, this Maven plugin can be implemented as a Post-Build Step in a Maven Job.

== Usage
Prior to uploading a BOM (Bill Of Materials) to the Dependency-Track server for analysis, it needs to be generated.

=== Set Post Steps
. Select the bullet `Run only of build succeeds`, to reduce the amount of irrelevant post build actions.

=== Generate BOM
. Add a post-build step of the type `Invoke top-level Maven targets`.
.. Choose a relevant Maven Version.
.. Insert the Goal `org.cyclonedx:cyclonedx-maven-plugin:1.4.1:makeBom`.
.. Click on `Advanced`, and add the path to the project's pom-file.

=== Upload BOM
. Add a post-build step of the type `Invoke top-level Maven targets`.
.. Choose a relevant Maven Version.
.. Insert the Goal `dk.topdanmark.maven.plugin:dependency-track-maven-plugin:2.0.3:uploadBom -DdTrackHostUrl=https://dtrack.domain.org -DapiKey=1234567890 -DpathToBom=[path-to-bom-file]`
