= Use Maven goal uploadBom
Jon Brohauge <jnz@topdanmark.dk>
v1.0, 2019-08-27

The Maven goal: *uploadBom* allows for upload of a generated BOM (Bill Of Materials) file to be analysed by Dependency-Track.

Prior to uploading a BOM (Bill Of Materials) to the Dependency-Track server for analysis, it needs to be generated.

== Usage

=== Generate BOM

Insert the following plugin information to generate a BOM
[source,xml]
....
<plugin>
    <groupId>org.cyclonedx</groupId>
    <artifactId>cyclonedx-maven-plugin</artifactId>
    <version>1.4.1</version>
    <executions>
        <execution>
            <phase>verify</phase>
            <goals>
                <goal>makeBom</goal>
            </goals>
        </execution>
    </executions>
</plugin>
....

=== Upload Bom

Insert the following plugin information to upload The BOM file.
[source,xml]
....
<plugin>
    <groupId>dk.topdanmark.maven.plugin</groupId>
    <artifactId>dependency-track-maven-plugin</artifactId>
    <version>2.0.3</version>
    <configuration>
        <debugStatus>true</debugStatus>
    </configuration>
    <executions>
        <execution>
            <phase>verify</phase>
            <goals>
                <goal>uploadBom</goal>
            </goals>
        </execution>
    </executions>
</plugin>
....

=== Optional properties

bomFilePath:: This property allows for setting a specific path to the bom.xml file.
+
It defaults to `target/bom.xml`

=== Example

The following example is a minimal configuration.
[source,xml]
....
<build>
    <plugins>
        <plugin>
            <groupId>org.cyclonedx</groupId>
            <artifactId>cyclonedx-maven-plugin</artifactId>
            <version>1.4.1</version>
            <executions>
                <execution>
                    <phase>verify</phase>
                    <goals>
                        <goal>makeBom</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
        <plugin>
            <groupId>dk.topdanmark.maven.plugin</groupId>
            <artifactId>dependency-track-maven-plugin</artifactId>
            <version>2.0.3</version>
            <configuration>
                <dTrackHostUrl>https://dtrack.domain.org</dTrackHostUrl>
                <apiKey>1234567890</apiKey>
                <debugStatus>true</debugStatus>
            </configuration>
            <executions>
                <execution>
                    <phase>verify</phase>
                    <goals>
                        <goal>uploadBom</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
....

=== Command line usage

It is possible to use the plugin directly on the command line:
`mvn clean test package org.cyclonedx:1.4.1:makeBom dk.topdanmark.maven.plugin:2.0.3:dependency-track-maven-plugin:uploadBom -DdTrackHostUrl=https://dtrack.domain.org -DapiKey=1234567890`
